services:
  db:
    image: postgres:18
    container_name: study-pgsql
    environment:
      POSTGRES_USER: study
      POSTGRES_PASSWORD: study123
      POSTGRES_DB: study_fastapi
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U study -d study_fastapi"]
      interval: 3s
      timeout: 3s
      retries: 10

  app:
    build: .
    container_name: study-app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg://study:study123@db:5432/study_fastapi
    depends_on:
      db:
        condition: service_healthy

  mysql:
    image: mysql:8.4
    container_name: study-mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: study_fastapi
      MYSQL_USER: study
      MYSQL_PASSWORD: study123
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 3s
      timeout: 3s
      retries: 10
  redis:
    image: redis:8.10
    container_name: study-redis
    command: redis-server --requirepass redis123 --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a redis123 ping | grep PONG"]
      interval: 3s
      timeout: 3s
      retries: 10

volumes:
  pgdata:
  mysqldata:
  redisdata:
