"""add embedding_chunks table

Revision ID: 6425a2b27924
Revises: 210d9d884dd9
Create Date: 2026-10-08 19:47:22.479354

"""

from typing import Sequence, Union
from pgvector.sqlalchemy import VECTOR
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6425a2b27924"
down_revision: Union[str, Sequence[str], None] = "210d9d884dd9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "embedding_chunks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="块ID"),
        sa.Column("news_id", sa.Integer(), nullable=False, comment="所属新闻ID"),
        sa.Column("chunk_index", sa.Integer(), nullable=False, comment="块序号"),
        sa.Column("content", sa.Text(), nullable=False, comment="块序号"),
        sa.Column("embedding", VECTOR(dim=1024), nullable=False, comment="1024维语义向量"),
        sa.Column("create_at", sa.DateTime(), nullable=False, comment="创建时间"),
        sa.Column("update_at", sa.DateTime(), nullable=False, comment="更新时间"),
        sa.ForeignKeyConstraint(["news_id"], ["news.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("embedding_chunks")
    # ### end Alembic commands ###
