"""messages add tool call columns

Revision ID: 7f2870eddaa5
Revises: 56f9e8da776c
Create Date: 2026-10-06 12:29:43.796223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f2870eddaa5'
down_revision: Union[str, Sequence[str], None] = '56f9e8da776c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('tool_call_id', sa.String(length=64), nullable=True))
    op.add_column('messages', sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('messages', 'tool_calls')
    op.drop_column('messages', 'tool_call_id')
    # ### end Alembic commands ###
