"""init tables

Revision ID: 9e37cedf70f5
Revises: 
Create Date: 2026-09-21 15:02:03.700627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e37cedf70f5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='分类ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='分类名称'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('create_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False, comment='密码（加密存储）'),
    sa.Column('gender', sa.Enum('male', 'female', 'unknown', name='gender'), nullable=True, comment='性别'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('news',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='新闻ID'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='新闻标题'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='新闻简介'),
    sa.Column('content', sa.Text(), nullable=False, comment='新闻内容'),
    sa.Column('image', sa.String(length=255), nullable=True, comment='封面图片URL'),
    sa.Column('author', sa.String(length=50), nullable=True, comment='作者'),
    sa.Column('category_id', sa.Integer(), nullable=False, comment='分类ID'),
    sa.Column('views', sa.Integer(), nullable=False, comment='浏览量'),
    sa.Column('publish_time', sa.DateTime(), nullable=False, comment='发布时间'),
    sa.Column('create_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['category_id'], ['news_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('fk_news_category_idx', 'news', ['category_id'], unique=False)
    op.create_index('idx_publish_time', 'news', ['publish_time'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('views', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('published', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='收藏ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('news_id', sa.Integer(), nullable=False, comment='新闻ID'),
    sa.Column('create_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'news_id', name='user_news_unique')
    )
    op.create_index('fk_favorite_news_idx', 'favorite', ['news_id'], unique=False)
    op.create_index('fk_favorite_user_idx', 'favorite', ['user_id'], unique=False)
    op.create_table('history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='历史ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('news_id', sa.Integer(), nullable=False, comment='新闻ID'),
    sa.Column('view_time', sa.DateTime(), nullable=False, comment='浏览时间'),
    sa.Column('create_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('fk_history_news_idx', 'history', ['news_id'], unique=False)
    op.create_index('fk_history_user_idx', 'history', ['user_id'], unique=False)
    op.create_index('idx_view_time', 'history', ['view_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_view_time', table_name='history')
    op.drop_index('fk_history_user_idx', table_name='history')
    op.drop_index('fk_history_news_idx', table_name='history')
    op.drop_table('history')
    op.drop_index('fk_favorite_user_idx', table_name='favorite')
    op.drop_index('fk_favorite_news_idx', table_name='favorite')
    op.drop_table('favorite')
    op.drop_table('posts')
    op.drop_index('idx_publish_time', table_name='news')
    op.drop_index('fk_news_category_idx', table_name='news')
    op.drop_table('news')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('news_category')
    # ### end Alembic commands ###
