"""add bio to users

Revision ID: ce8f923bf46a
Revises: 612bcc649205
Create Date: 2026-09-16 15:53:12.186874

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ce8f923bf46a"
down_revision: str | Sequence[str] | None = "612bcc649205"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("bio", sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "bio")
    # ### end Alembic commands ###
